---
title: Stand Out Photo Forum
timezone: UTC
collections:
  assets:
    title: Assets
    output: true
    permalink: "/assets/:path/"
  events:
    title: Events
    output: true
    permalink: "/events/:path/"
  posts:
    title: Posts
    output: true
  regions:
    title: Regions
    output: true
    permalink: "/regions/:path/"
  seminars:
    title: Seminars
    output: true
    permalink: "/seminars/:path/"
  speakers:
    title: Speakers
    output: true
    permalink: "/:path/"
    layout: speaker
    date: 2016-08-08 12:36:52.000000000 Z
    collection: speakers
    city: New York City, Chicago, Los Angeles, London, Paris
    headshot: https://placehold.it/600x600
    featured-image: https://placehold.it/600x800
    bio: Lorem ipsum dolor sit amet
  sponsors:
    title: Sponsors
    output: true
    permalink: "/sponsors/:path/"
  uploads:
    title: Uploads
    output: true
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: https://mollympierce1.github.io/standout-2
url: https://yourdomain.com
email: your-email@domain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
