# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stand Out Photo Forum
email: your-email@domain.com
collections:
  events:
    title: Events
    output: true
    permalink: "/events/:path/"
  regions:
    title: Regions
    output: true
    permalink: "/regions/:path/"
  posts:
    title: Posts
    output: true
  seminars:
    title: Seminars
    output: true
    permalink: "/seminars/:path/"
  speakers:
    title: Speakers
    output: true
    permalink: "/speakers/:path/"
    layout: speaker
    date: 2016-08-08 12:36:52 Z
    collection: speakers
    city: New York City, Chicago, Los Angeles, London, Paris
    headshot: http://placehold.it/600x600
    featured-image: http://placehold.it/600x800
    bio: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    layout: speaker
    facebook-url: #
    youtube-url: #
    vimeo-url: #
    instagram-url: #
    linkedin-url: #
  sponsors:
    title: Sponsors
    output: true
    permalink: "/sponsors/:path/"
  assets:
    title: Assets
    output: true
    permalink: "/assets/:path/"
  uploads:
    title: Uploads
    output: true
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
